/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registropaciente;

import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class MenuMedico extends javax.swing.JFrame {

    /**
     * Creates new form MenuMed
     */
    public MenuMedico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        Creditos = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Receta = new javax.swing.JButton();
        SALUDIcon = new javax.swing.JLabel();
        HospitalPC = new javax.swing.JLabel();
        FondoIcon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perfil del Médico");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(0, 204, 51));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Fondo.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        Creditos.setText("Créditos");
        Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditosActionPerformed(evt);
            }
        });
        Fondo.add(Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Fondo.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        Receta.setText("Recetar");
        Receta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecetaActionPerformed(evt);
            }
        });
        Fondo.add(Receta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, 60));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 200));

        SALUDIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/highlight_Logo_Salud_1.jpg"))); // NOI18N
        getContentPane().add(SALUDIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 80));

        HospitalPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hospital.jpg"))); // NOI18N
        getContentPane().add(HospitalPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 100, 100));

        FondoIcon.setBackground(new java.awt.Color(255, 255, 255));
        FondoIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        FondoIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(FondoIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        InicioSesion close = new InicioSesion();
        close.Cerrar();
    }//GEN-LAST:event_SalirActionPerformed

    private void CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInternalMessageDialog(null, "Este trabajo fue realizado por: \n Axel Ivan Arroyo Lara \n Pablo Silva Norena \n Miguel Angel Garcia Arrieta");
    }//GEN-LAST:event_CreditosActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        InicioSesion Ingresar = new InicioSesion();
        Ingresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void RecetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecetaActionPerformed
        // TODO add your handling code here:
        Recetario Ingresar = new Recetario();
        Ingresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RecetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Creditos;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel FondoIcon;
    private javax.swing.JLabel HospitalPC;
    private javax.swing.JButton Receta;
    private javax.swing.JLabel SALUDIcon;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Volver;
    // End of variables declaration//GEN-END:variables
}
