/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registropaciente;

import java.sql.*;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class Recetario extends javax.swing.JFrame {

    Conexion obj = new Conexion();
    Connection obj2 = obj.CadConn();
    
    /**
     * Creates new form Recetario
     */
    public Recetario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
public void DecidirVolver(){
    String Botones[] = {"Inicio de Sesión","Menú"};
        int Opcion = JOptionPane.showOptionDialog(this, "¿A donde desea volver?", "Volver", 0, 0, null, Botones, this);
        
        if(Opcion == JOptionPane.YES_OPTION){
        InicioSesion ir = new InicioSesion();
        ir.setVisible(true);
        }
        else if(Opcion == JOptionPane.NO_OPTION){
        MenuMedico ir = new MenuMedico();
        ir.setVisible(true);
        this.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parte2 = new javax.swing.JPanel();
        HospitalPC = new javax.swing.JLabel();
        LBLTituloA = new javax.swing.JLabel();
        LBLTituloB = new javax.swing.JLabel();
        LBLPad = new javax.swing.JLabel();
        LBLRecom = new javax.swing.JLabel();
        LBLOb = new javax.swing.JLabel();
        LBLMed = new javax.swing.JLabel();
        LBLContin = new javax.swing.JLabel();
        LBLDias = new javax.swing.JLabel();
        TxtPad = new javax.swing.JTextArea();
        TxtRecSuger = new javax.swing.JTextArea();
        TxtMedicar = new javax.swing.JTextField();
        SpinContin = new javax.swing.JSpinner();
        r5 = new javax.swing.JPanel();
        r6 = new javax.swing.JPanel();
        Separador1 = new javax.swing.JSeparator();
        Separador2 = new javax.swing.JSeparator();
        Separador3 = new javax.swing.JSeparator();
        BtnVolver = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        Parte1 = new javax.swing.JPanel();
        SALUD = new javax.swing.JLabel();
        LblTitulo1 = new javax.swing.JLabel();
        LblTitulo2 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblAPaterno = new javax.swing.JLabel();
        LblAMaterno = new javax.swing.JLabel();
        LblEdad = new javax.swing.JLabel();
        LblAños = new javax.swing.JLabel();
        LblSexo = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        o1 = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        LBLSint = new javax.swing.JLabel();
        LBLLapsoA = new javax.swing.JLabel();
        LBLLapsoB = new javax.swing.JLabel();
        LBLRegion = new javax.swing.JLabel();
        r1 = new javax.swing.JPanel();
        r1r1 = new javax.swing.JPanel();
        Date = new javax.swing.JPanel();
        TxtName = new javax.swing.JTextField();
        TxtSex = new javax.swing.JTextField();
        TxtAMatern = new javax.swing.JTextField();
        TxtRegCrp = new javax.swing.JTextField();
        TxtSint = new javax.swing.JTextArea();
        TxtLapso = new javax.swing.JTextField();
        TxtYears = new javax.swing.JTextField();
        TxtAPatern = new javax.swing.JTextField();
        DtCons = new com.toedter.calendar.JDateChooser();
        r2 = new javax.swing.JPanel();
        r3 = new javax.swing.JPanel();
        Separador4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recetario");
        setMinimumSize(new java.awt.Dimension(800, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Parte2.setBackground(new java.awt.Color(255, 255, 255));
        Parte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte2.setMaximumSize(new java.awt.Dimension(800, 250));
        Parte2.setMinimumSize(new java.awt.Dimension(800, 250));
        Parte2.setPreferredSize(new java.awt.Dimension(800, 250));
        Parte2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HospitalPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hospital.jpg"))); // NOI18N
        Parte2.add(HospitalPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 100, 110));

        LBLTituloA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBLTituloA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTituloA.setText("Diagnóstico ");
        Parte2.add(LBLTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 120, -1));

        LBLTituloB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LBLTituloB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTituloB.setText("General");
        LBLTituloB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Parte2.add(LBLTituloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, -1));

        LBLPad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLPad.setText("Padecimiento:");
        Parte2.add(LBLPad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        LBLRecom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLRecom.setText("Recomendaciones");
        Parte2.add(LBLRecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        LBLOb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLOb.setText("u Observaciones:");
        Parte2.add(LBLOb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        LBLMed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLMed.setText("Medicar:");
        Parte2.add(LBLMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 20));

        LBLContin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLContin.setText("Continuidad:");
        Parte2.add(LBLContin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 20));

        LBLDias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBLDias.setText("días.");
        Parte2.add(LBLDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 20));

        TxtPad.setColumns(20);
        TxtPad.setRows(5);
        TxtPad.setToolTipText("Escribe aquí su observación y posible padecimiento, separe con comas.");
        TxtPad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte2.add(TxtPad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 220, 50));

        TxtRecSuger.setColumns(20);
        TxtRecSuger.setRows(5);
        TxtRecSuger.setToolTipText("Escribe aquí su observación y posible padecimiento, separe con comas.");
        TxtRecSuger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte2.add(TxtRecSuger, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 50));

        TxtMedicar.setToolTipText("Medicamento a Aplicar.");
        Parte2.add(TxtMedicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 120, -1));

        SpinContin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        Parte2.add(SpinContin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 50, -1));

        r5.setBackground(new java.awt.Color(255, 255, 255));
        Parte2.add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 260, 10));

        r6.setBackground(new java.awt.Color(255, 255, 255));
        Parte2.add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 0, 260, 10));
        Parte2.add(Separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 400, -1));

        Separador2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Parte2.add(Separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 20, 49));

        Separador3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Parte2.add(Separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 10, 49));

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        Parte2.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        Parte2.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        Parte2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        getContentPane().add(Parte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 270));

        Parte1.setBackground(new java.awt.Color(255, 255, 255));
        Parte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.setMaximumSize(new java.awt.Dimension(800, 400));
        Parte1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/highlight_Logo_Salud_1.jpg"))); // NOI18N
        Parte1.add(SALUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 80));

        LblTitulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblTitulo1.setText("Formato Único de Consulta");
        Parte1.add(LblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        LblTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTitulo2.setText("Recetario");
        Parte1.add(LblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        LblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblNombre.setText("Nombre:");
        Parte1.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        LblAPaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblAPaterno.setText("Apellido Paterno:");
        Parte1.add(LblAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 20));

        LblAMaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblAMaterno.setText("Apellido Materno:");
        Parte1.add(LblAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 20));

        LblEdad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblEdad.setText("Edad:");
        Parte1.add(LblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        LblAños.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblAños.setText("años.");
        Parte1.add(LblAños, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, 20));

        LblSexo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblSexo.setText("Sexo:");
        Parte1.add(LblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        o.setBackground(new java.awt.Color(0, 0, 0));
        o.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1, 100));

        o1.setBackground(new java.awt.Color(0, 0, 0));
        o1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.add(o1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 220, 60));

        o2.setBackground(new java.awt.Color(0, 0, 0));
        o2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.add(o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 0, 1, 100));

        LBLSint.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLSint.setText("Síntomas:");
        Parte1.add(LBLSint, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        LBLLapsoA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLLapsoA.setText("Lapso del Padecimiento:");
        Parte1.add(LBLLapsoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        LBLLapsoB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBLLapsoB.setText("días.");
        Parte1.add(LBLLapsoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 20));

        LBLRegion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLRegion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLRegion.setText("Región Corporal:");
        Parte1.add(LBLRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 130, 20));

        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r1r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.add(r1r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 220, 50));

        Date.setBackground(new java.awt.Color(255, 255, 255));
        Date.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de la Consulta"));
        Date.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtName.setEditable(false);
        TxtName.setToolTipText("Su Nombre Completo.");
        Date.add(TxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));

        TxtSex.setEditable(false);
        TxtSex.setToolTipText("Su Apellido Paterno.");
        Date.add(TxtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        TxtAMatern.setEditable(false);
        TxtAMatern.setToolTipText("Su Apellido Materno.");
        Date.add(TxtAMatern, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 110, -1));

        TxtRegCrp.setEditable(false);
        TxtRegCrp.setToolTipText("Su Apellido Paterno.");
        Date.add(TxtRegCrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 120, -1));

        TxtSint.setEditable(false);
        TxtSint.setColumns(20);
        TxtSint.setRows(5);
        TxtSint.setToolTipText("Escribe aquí su observación y posible padecimiento, separe con comas.");
        TxtSint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Date.add(TxtSint, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 220, -1));

        TxtLapso.setEditable(false);
        TxtLapso.setToolTipText("Tiempo de duración presente del padecimiento.");
        Date.add(TxtLapso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 50, 20));

        TxtYears.setEditable(false);
        TxtYears.setToolTipText("Su Edad actual.");
        Date.add(TxtYears, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 50, -1));

        TxtAPatern.setEditable(false);
        TxtAPatern.setToolTipText("Su Apellido Paterno.");
        Date.add(TxtAPatern, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 120, -1));

        DtCons.setBackground(new java.awt.Color(255, 255, 255));
        Date.add(DtCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        r1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 60));

        Parte1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        r2.setBackground(new java.awt.Color(255, 255, 255));
        Parte1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 350, 260, 10));

        r3.setBackground(new java.awt.Color(255, 255, 255));
        Parte1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 350, 260, 10));

        Separador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Parte1.add(Separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 580, 2));

        getContentPane().add(Parte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        DecidirVolver();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        InicioSesion close = new InicioSesion();
        close.Cerrar();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        long t;
        Date date = DtCons.getDate();
        t = date.getTime();
        java.sql.Date FechaConsulta = new java.sql.Date(t);
        
        try{
        PreparedStatement Guardar = obj2.prepareStatement("INSERT INTO datosmedicar(FechaCons, Padecimiento, Medicar, Observaciones, Continuidad)VALUES(?,?,?,?,?)"); 
        Guardar.setDate(1, FechaConsulta);
        Guardar.setString(2, TxtPad.getText());
        Guardar.setString(3, TxtMedicar.getText());
        Guardar.setString(4, TxtRecSuger.getText());
        Guardar.setInt(5, Integer.parseInt(SpinContin.getValue().toString()));
        Guardar.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Datos almacenados correctamente");        
        }
        catch (SQLException ex) {
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recetario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPanel Date;
    private com.toedter.calendar.JDateChooser DtCons;
    private javax.swing.JLabel HospitalPC;
    private javax.swing.JLabel LBLContin;
    private javax.swing.JLabel LBLDias;
    private javax.swing.JLabel LBLLapsoA;
    private javax.swing.JLabel LBLLapsoB;
    private javax.swing.JLabel LBLMed;
    private javax.swing.JLabel LBLOb;
    private javax.swing.JLabel LBLPad;
    private javax.swing.JLabel LBLRecom;
    private javax.swing.JLabel LBLRegion;
    private javax.swing.JLabel LBLSint;
    private javax.swing.JLabel LBLTituloA;
    private javax.swing.JLabel LBLTituloB;
    private javax.swing.JLabel LblAMaterno;
    private javax.swing.JLabel LblAPaterno;
    private javax.swing.JLabel LblAños;
    private javax.swing.JLabel LblEdad;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo2;
    private javax.swing.JPanel Parte1;
    private javax.swing.JPanel Parte2;
    private javax.swing.JLabel SALUD;
    private javax.swing.JSeparator Separador1;
    private javax.swing.JSeparator Separador2;
    private javax.swing.JSeparator Separador3;
    private javax.swing.JSeparator Separador4;
    private javax.swing.JSpinner SpinContin;
    public static javax.swing.JTextField TxtAMatern;
    public static javax.swing.JTextField TxtAPatern;
    public static javax.swing.JTextField TxtLapso;
    private javax.swing.JTextField TxtMedicar;
    public static javax.swing.JTextField TxtName;
    private javax.swing.JTextArea TxtPad;
    private javax.swing.JTextArea TxtRecSuger;
    public static javax.swing.JTextField TxtRegCrp;
    public static javax.swing.JTextField TxtSex;
    public static javax.swing.JTextArea TxtSint;
    public static javax.swing.JTextField TxtYears;
    private javax.swing.JLabel o;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel o2;
    private javax.swing.JPanel r1;
    private javax.swing.JPanel r1r1;
    private javax.swing.JPanel r2;
    private javax.swing.JPanel r3;
    private javax.swing.JPanel r5;
    private javax.swing.JPanel r6;
    // End of variables declaration//GEN-END:variables
}
