/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registropaciente;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Date;
/**
 *
 * @author garci
 */
public class RegistroPaciente extends javax.swing.JFrame {

    Conexion obj = new Conexion();
    Connection obj2 = obj.CadConn();
    /**
     * Creates new form RegistroPaciente
     */
    public RegistroPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
public void CheckSexo(){
    Masculino.setEnabled(true);
    Femenino.setEnabled(true);
    if (Masculino.isSelected()){
            Femenino.setEnabled(false);
        }
    else if (Femenino.isSelected()){
        Masculino.setEnabled(false);
    }
}
public void Volver(){
    String Botones[] = {"Inicio de Sesión","Menú"};
        int Opcion = JOptionPane.showOptionDialog(this, "¿A donde desea volver?", "Volver", 0, 0, null, Botones, this);
        
        if(Opcion == JOptionPane.YES_OPTION){
        InicioSesion entrar = new InicioSesion();
        entrar.setVisible(true);
        }
        else if(Opcion == JOptionPane.NO_OPTION){
        MenuDoctor ir = new MenuDoctor();
        ir.setVisible(true);
        this.setVisible(false);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parte1 = new javax.swing.JPanel();
        SALUD = new javax.swing.JLabel();
        LblTituloA = new javax.swing.JLabel();
        LblTituloB = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblAPaterno = new javax.swing.JLabel();
        LblAMaterno = new javax.swing.JLabel();
        LblFechaNacim = new javax.swing.JLabel();
        LblEdad = new javax.swing.JLabel();
        LblEdadd = new javax.swing.JLabel();
        LblTelefono = new javax.swing.JLabel();
        LblSexo = new javax.swing.JLabel();
        LblEstado = new javax.swing.JLabel();
        LblCiudad = new javax.swing.JLabel();
        LblCodigoPostal = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        o1 = new javax.swing.JLabel();
        o2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtAP = new javax.swing.JTextField();
        TxtAM = new javax.swing.JTextField();
        TxtTel = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        TxtCiudad = new javax.swing.JTextField();
        TxtCodPostal = new javax.swing.JTextField();
        Masculino = new javax.swing.JCheckBox();
        Femenino = new javax.swing.JCheckBox();
        SpinEdad = new javax.swing.JSpinner();
        r1 = new javax.swing.JPanel();
        r1r1 = new javax.swing.JPanel();
        Date = new javax.swing.JPanel();
        DtFechaReg = new com.toedter.calendar.JDateChooser();
        r2 = new javax.swing.JPanel();
        r3 = new javax.swing.JPanel();
        DtFechaNac = new com.toedter.calendar.JDateChooser();
        Parte2 = new javax.swing.JPanel();
        HospitalPC = new javax.swing.JLabel();
        LBLTituloA = new javax.swing.JLabel();
        LBLTituloB = new javax.swing.JLabel();
        LBLDiagnost = new javax.swing.JLabel();
        LBLRegion = new javax.swing.JLabel();
        LBLLapsoA = new javax.swing.JLabel();
        LBLLapsoB = new javax.swing.JLabel();
        TXTDiagnost = new javax.swing.JTextArea();
        SpinPad = new javax.swing.JSpinner();
        ComboRegCorp = new javax.swing.JComboBox<>();
        r5 = new javax.swing.JPanel();
        r6 = new javax.swing.JPanel();
        BtnVolver = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Internado");
        setMinimumSize(new java.awt.Dimension(816, 689));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Parte1.setBackground(new java.awt.Color(255, 255, 255));
        Parte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.setMaximumSize(new java.awt.Dimension(800, 400));
        Parte1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/highlight_Logo_Salud_1.jpg"))); // NOI18N
        Parte1.add(SALUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 80));

        LblTituloA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblTituloA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTituloA.setText("Datos del Paciente");
        Parte1.add(LblTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 120, -1));

        LblTituloB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTituloB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTituloB.setText("Beneficiario");
        LblTituloB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Parte1.add(LblTituloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, -1));

        LblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblNombre.setText("Nombre:");
        Parte1.add(LblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 20));

        LblAPaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblAPaterno.setText("Apellido Paterno:");
        Parte1.add(LblAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 20));

        LblAMaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblAMaterno.setText("Apellido Materno:");
        Parte1.add(LblAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 20));

        LblFechaNacim.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblFechaNacim.setText("Fecha de Nacimiento:");
        Parte1.add(LblFechaNacim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        LblEdad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblEdad.setText("Edad:");
        Parte1.add(LblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        LblEdadd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblEdadd.setText("años.");
        Parte1.add(LblEdadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 20));

        LblTelefono.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblTelefono.setText("Teléfono:");
        Parte1.add(LblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, 20));

        LblSexo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblSexo.setText("Sexo:");
        Parte1.add(LblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        LblEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblEstado.setText("Estado:");
        Parte1.add(LblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        LblCiudad.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblCiudad.setText("Ciudad:");
        Parte1.add(LblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        LblCodigoPostal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LblCodigoPostal.setText("C.P:");
        Parte1.add(LblCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        o.setBackground(new java.awt.Color(0, 0, 0));
        o.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1, 100));

        o1.setBackground(new java.awt.Color(0, 0, 0));
        o1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.add(o1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 220, 60));

        o2.setBackground(new java.awt.Color(0, 0, 0));
        o2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte1.add(o2, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 0, 1, 100));

        TxtNombre.setToolTipText("Su Nombre Completo.");
        Parte1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));

        TxtAP.setToolTipText("Su Apellido Paterno.");
        Parte1.add(TxtAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 120, -1));

        TxtAM.setToolTipText("Su Apellido Materno.");
        Parte1.add(TxtAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 110, -1));

        TxtTel.setToolTipText("Su Número de Teléfono (Fijo,Casa,Celular).");
        Parte1.add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 140, -1));

        TxtEstado.setToolTipText("El Estado en el que reside.");
        Parte1.add(TxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 130, -1));

        TxtCiudad.setToolTipText("La Ciudad en la que reside.");
        Parte1.add(TxtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 130, -1));

        TxtCodPostal.setToolTipText("Código Postal de su Ciudad.");
        Parte1.add(TxtCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 130, -1));

        Masculino.setText("Masculino");
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });
        Parte1.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        Femenino.setText("Femenino");
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });
        Parte1.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        SpinEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        Parte1.add(SpinEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, -1));

        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        r1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        r1r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.add(r1r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 220, 50));

        Date.setBackground(new java.awt.Color(255, 255, 255));
        Date.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de la Consulta"));
        Date.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DtFechaReg.setBackground(new java.awt.Color(255, 255, 255));
        Date.add(DtFechaReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, -1));

        r1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 60));

        Parte1.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 100));

        r2.setBackground(new java.awt.Color(255, 255, 255));
        Parte1.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 390, 260, 10));

        r3.setBackground(new java.awt.Color(255, 255, 255));
        Parte1.add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 390, 260, 10));
        Parte1.add(DtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, -1));

        getContentPane().add(Parte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        Parte2.setBackground(new java.awt.Color(255, 255, 255));
        Parte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte2.setMaximumSize(new java.awt.Dimension(800, 250));
        Parte2.setMinimumSize(new java.awt.Dimension(800, 250));
        Parte2.setPreferredSize(new java.awt.Dimension(800, 250));
        Parte2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HospitalPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hospital.jpg"))); // NOI18N
        Parte2.add(HospitalPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 100, 110));
        HospitalPC.getAccessibleContext().setAccessibleParent(HospitalPC);

        LBLTituloA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBLTituloA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTituloA.setText("Datos ");
        Parte2.add(LBLTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 120, -1));

        LBLTituloB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LBLTituloB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTituloB.setText("Médicos");
        LBLTituloB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Parte2.add(LBLTituloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 120, -1));

        LBLDiagnost.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLDiagnost.setText("Síntomas (Especifique):");
        Parte2.add(LBLDiagnost, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        LBLRegion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLRegion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLRegion.setText("Región Corporal:");
        Parte2.add(LBLRegion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 20));

        LBLLapsoA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LBLLapsoA.setText("Lapso del Padecimiento:");
        Parte2.add(LBLLapsoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        LBLLapsoB.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBLLapsoB.setText("días.");
        Parte2.add(LBLLapsoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, 20));

        TXTDiagnost.setColumns(20);
        TXTDiagnost.setRows(5);
        TXTDiagnost.setToolTipText("Escribe aquí su observación y posible padecimiento, separe con comas.");
        TXTDiagnost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Parte2.add(TXTDiagnost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 220, -1));

        SpinPad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        Parte2.add(SpinPad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 50, -1));

        ComboRegCorp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Cabeza", "Cuello", "Miembro Superior", "Tórax", "Abdomen", "Pelvis", "Miembro Superior" }));
        ComboRegCorp.setToolTipText("Selecciona la Región del cuerpo donde se presenta el siniestro.");
        Parte2.add(ComboRegCorp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        r5.setBackground(new java.awt.Color(255, 255, 255));
        Parte2.add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 260, 10));

        r6.setBackground(new java.awt.Color(255, 255, 255));
        Parte2.add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 0, 260, 10));

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        Parte2.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        Parte2.add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        Parte2.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        Parte2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));
        Parte2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 201, 530, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Parte2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 20, 48));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Parte2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 201, -1, 48));

        getContentPane().add(Parte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 800, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
        CheckSexo();
    }//GEN-LAST:event_FemeninoActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
        CheckSexo();
    }//GEN-LAST:event_MasculinoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        // TODO add your handling code here:
        Volver();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        InicioSesion close = new InicioSesion();
        close.Cerrar();
    }//GEN-LAST:event_BtnSalirActionPerformed
//        Recetario.TxtName.setText(TxtNombre.getText());
     //   Recetario.TxtAPatern.setText(TxtAP.getText());
     //   Recetario.TxtAMatern.setText(TxtAM.getText());
     //   Recetario.TxtYears.setText(SpinEdad.getValue().toString());
     //   Recetario.TxtSint.setText(TXTDiagnost.getText());
     //   Recetario.TxtLapso.setText(SpinPad.getValue().toString());
     //   Recetario.TxtRegCrp.setText(ComboRegCorp.getSelectedItem().toString());
     //   
     //   if(Masculino.isSelected()){     
     //   Recetario.TxtSex.setText(Masculino.getText());
     //   }
     //   else if(Femenino.isSelected()){
     //   Recetario.TxtSex.setText(Femenino.getText());
     // }
    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        TxtNombre.setText(null);
        TxtAP.setText(null);
        TxtAM.setText(null);
        DtFechaNac.setDate(null);
        DtFechaReg.setDate(null);
        SpinEdad.setValue(1);
        TxtTel.setText(null);
        TxtEstado.setText(null);
        TxtCiudad.setText(null);
        TxtCodPostal.setText(null);
        SpinPad.setValue(1);
        TXTDiagnost.setText(null);
        Femenino.setSelected(false);
        Masculino.setSelected(false);
        ComboRegCorp.setSelectedItem("Seleccionar...");
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:   
        long d,c;
    Date date = DtFechaReg.getDate();
    d = date.getTime();
    java.sql.Date FechaRegistro = new java.sql.Date(d);
    
    Date fecha = DtFechaNac.getDate();
    c = fecha.getTime();
    java.sql.Date FechaNacim = new java.sql.Date(c);
    
    try {
        PreparedStatement Guardar = obj2.prepareStatement("INSERT INTO datospaciente(FechaReg, Nombre, APaterno, AMaterno, FechaNac, Edad, Teléfono, Sexo, Estado, Ciudad, CP, Sintomas, RegionC, Lapso)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        Guardar.setDate(1,FechaRegistro);
        Guardar.setString(2,TxtNombre.getText());
        Guardar.setString(3, TxtAP.getText());
        Guardar.setString(4, TxtAM.getText());
        Guardar.setDate(5, FechaNacim);
        Guardar.setInt(6, Integer.parseInt(SpinEdad.getValue().toString()));
        Guardar.setString(7, TxtTel.getText());
            if(Masculino.isSelected()){     
        Guardar.setString(8, Masculino.getText());
            }
            else if(Femenino.isSelected()){
        Guardar.setString(8, Femenino.getText());
            }
        Guardar.setString(9, TxtEstado.getText());
        Guardar.setString(10, TxtCiudad.getText());
        Guardar.setString(11, TxtCodPostal.getText());
        Guardar.setString(12, TXTDiagnost.getText());
        Guardar.setString(13, ComboRegCorp.getSelectedItem().toString());
        Guardar.setString(14, SpinPad.getValue().toString());
        Guardar.executeUpdate();
        JOptionPane.showMessageDialog(null, "Datos almacenados correctamente");
        }
        catch (SQLException ex) {
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JComboBox<String> ComboRegCorp;
    private javax.swing.JPanel Date;
    private com.toedter.calendar.JDateChooser DtFechaNac;
    private com.toedter.calendar.JDateChooser DtFechaReg;
    private javax.swing.JCheckBox Femenino;
    private javax.swing.JLabel HospitalPC;
    private javax.swing.JLabel LBLDiagnost;
    private javax.swing.JLabel LBLLapsoA;
    private javax.swing.JLabel LBLLapsoB;
    private javax.swing.JLabel LBLRegion;
    private javax.swing.JLabel LBLTituloA;
    private javax.swing.JLabel LBLTituloB;
    private javax.swing.JLabel LblAMaterno;
    private javax.swing.JLabel LblAPaterno;
    private javax.swing.JLabel LblCiudad;
    private javax.swing.JLabel LblCodigoPostal;
    private javax.swing.JLabel LblEdad;
    private javax.swing.JLabel LblEdadd;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblFechaNacim;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblSexo;
    private javax.swing.JLabel LblTelefono;
    private javax.swing.JLabel LblTituloA;
    private javax.swing.JLabel LblTituloB;
    private javax.swing.JCheckBox Masculino;
    private javax.swing.JPanel Parte1;
    private javax.swing.JPanel Parte2;
    private javax.swing.JLabel SALUD;
    private javax.swing.JSpinner SpinEdad;
    private javax.swing.JSpinner SpinPad;
    private javax.swing.JTextArea TXTDiagnost;
    private javax.swing.JTextField TxtAM;
    private javax.swing.JTextField TxtAP;
    private javax.swing.JTextField TxtCiudad;
    private javax.swing.JTextField TxtCodPostal;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel o;
    private javax.swing.JLabel o1;
    private javax.swing.JLabel o2;
    private javax.swing.JPanel r1;
    private javax.swing.JPanel r1r1;
    private javax.swing.JPanel r2;
    private javax.swing.JPanel r3;
    private javax.swing.JPanel r5;
    private javax.swing.JPanel r6;
    // End of variables declaration//GEN-END:variables
}
